import type { Client } from "./types";

/**
 * Dados iniciais. Clientes ativos = exemplos para a ferramenta já nascer com
 * métricas reais. Leads = prospects levantados na pesquisa de Brasília/DF.
 * Tudo é editável e persiste no navegador (localStorage).
 */
export const SEED_CLIENTS: Client[] = [
  {
    id: "cli-atelie-norte",
    nome: "Ateliê Norte Studio",
    segmento: "Studio de fotografia",
    regiao: "Asa Norte",
    whatsapp: "(61) 99610-0042",
    instagram: "@atelienorte",
    email: "contato@atelienorte.com.br",
    status: "ativo",
    plano: "anual",
    valorPlano: 1100,
    manutencao: 50,
    contrato: "assinado",
    inicio: "2026-02-10",
    infra: {
      dominio: "atelienorte.com.br",
      registrador: "Registro.br",
      dominioVence: "2027-02-10",
      dominioCusto: 40,
      hospedagem: "Vercel",
      hospedagemVence: "2027-02-10",
      hospedagemCusto: 0,
    },
    pagamentos: [
      { id: "p1", descricao: "Plano anual 2026", valor: 1100, vencimento: "2026-02-10", status: "pago", pagoEm: "2026-02-09" },
      { id: "p2", descricao: "Manutenção · jun", valor: 50, vencimento: "2026-06-10", status: "pago", pagoEm: "2026-06-10" },
      { id: "p3", descricao: "Manutenção · jul", valor: 50, vencimento: "2026-07-10", status: "pago", pagoEm: "2026-07-11" },
      { id: "p4", descricao: "Manutenção · ago", valor: 50, vencimento: "2026-08-10", status: "pendente" },
    ],
    observacoes: "Cliente âncora. Indicou 2 leads. Renovação anual em fevereiro.",
  },
  {
    id: "cli-vitalis",
    nome: "Clínica Vitalis",
    segmento: "Clínica odontológica",
    regiao: "Águas Claras",
    whatsapp: "(61) 98120-7788",
    instagram: "@clinicavitalis",
    email: "adm@clinicavitalis.com.br",
    status: "pendente",
    plano: "semestral",
    valorPlano: 550,
    manutencao: 50,
    contrato: "assinado",
    inicio: "2026-05-01",
    infra: {
      dominio: "clinicavitalis.com.br",
      registrador: "Registro.br",
      dominioVence: "2027-05-01",
      dominioCusto: 40,
      hospedagem: "Vercel",
      hospedagemVence: "2027-05-01",
      hospedagemCusto: 0,
    },
    pagamentos: [
      { id: "p1", descricao: "Plano semestral", valor: 550, vencimento: "2026-05-01", status: "pago", pagoEm: "2026-05-02" },
      { id: "p2", descricao: "Manutenção · jul", valor: 50, vencimento: "2026-07-05", status: "pago", pagoEm: "2026-07-05" },
      { id: "p3", descricao: "Manutenção · ago", valor: 50, vencimento: "2026-08-05", status: "atrasado" },
    ],
    observacoes: "Manutenção de agosto em atraso — cobrar pelo WhatsApp.",
  },
  {
    id: "cli-donvicent",
    nome: "Don Vicent Barbearia",
    segmento: "Barbearia",
    regiao: "Vicente Pires",
    whatsapp: "(61) 98192-5491",
    instagram: "@donvicent.barbearia",
    status: "inadimplente",
    plano: "anual",
    valorPlano: 1100,
    manutencao: 50,
    contrato: "assinado",
    inicio: "2026-01-15",
    infra: {
      dominio: "donvicentbarbearia.com.br",
      registrador: "Hostinger",
      dominioVence: "2026-08-20",
      dominioCusto: 45,
      hospedagem: "Hostinger",
      hospedagemVence: "2026-08-20",
      hospedagemCusto: 180,
    },
    pagamentos: [
      { id: "p1", descricao: "Plano anual 2026", valor: 1100, vencimento: "2026-01-15", status: "pago", pagoEm: "2026-01-15" },
      { id: "p2", descricao: "Manutenção · jul", valor: 50, vencimento: "2026-07-15", status: "atrasado" },
      { id: "p3", descricao: "Manutenção · ago", valor: 50, vencimento: "2026-08-15", status: "pendente" },
    ],
    observacoes: "2 manutenções em aberto. Domínio vence dia 20 — renovar ou suspender.",
  },

  // ---- LEADS (pesquisa Brasília/DF) ----
  {
    id: "lead-glauber",
    nome: "Glauber Barbiere",
    segmento: "Barbearia por assinatura",
    regiao: "Guará I e II",
    whatsapp: "(61) 99380-2219",
    instagram: "@barbeariaglauberbarbiere",
    status: "lead",
    manutencao: 50,
    contrato: "nenhum",
    infra: {},
    pagamentos: [],
    observacoes:
      "2 unidades + modelo assinatura. Maior tíquete. Agenda pelo avec.beauty (terceiro). Ângulo: página que venda o plano e capture leads.",
  },
  {
    id: "lead-quebela",
    nome: "Que Bela Beauty",
    segmento: "Salão / estética",
    regiao: "Conjunto Nacional",
    whatsapp: "(61) 99823-2122",
    instagram: "@quebelabeauty",
    status: "lead",
    manutencao: 50,
    contrato: "nenhum",
    infra: {},
    pagamentos: [],
    observacoes: "Paga aluguel de shopping e não tem site — tem verba e valoriza imagem.",
  },
  {
    id: "lead-harmonizar",
    nome: "Harmonizar-se Estética Facial",
    segmento: "Harmonização facial",
    regiao: "Conjunto Nacional, 4º andar",
    whatsapp: "(61) 3964-8164",
    status: "lead",
    manutencao: 50,
    contrato: "nenhum",
    infra: {},
    pagamentos: [],
    observacoes:
      "Nota 5.0 no Google, tíquete de R$1–5k por procedimento e ZERO site. Concorrentes (Royal Face, Instituto Hera) todos têm site.",
  },
  {
    id: "lead-especialli",
    nome: "Especialli Odontologia",
    segmento: "Odontologia especializada",
    regiao: "Taguatinga (Alameda Shopping)",
    whatsapp: "(61) 99370-1463",
    instagram: "@especialliodont",
    status: "lead",
    manutencao: 50,
    contrato: "nenhum",
    infra: {},
    pagamentos: [],
    observacoes:
      "15 anos de mercado, só Instagram + diretórios. Ângulo: os diretórios lucram com o nome dela; site próprio captura esse tráfego.",
  },
  {
    id: "lead-savaya",
    nome: "Savaya Barbearia",
    segmento: "Barbearia",
    regiao: "Asa Sul",
    whatsapp: "(61) 99974-6529",
    instagram: "@barbeariasavaya",
    status: "lead",
    manutencao: 50,
    contrato: "nenhum",
    infra: {},
    pagamentos: [],
    observacoes: "Público de alta renda. Usa InBarber pra agendar.",
  },
  {
    id: "lead-mensclub",
    nome: "Barbearia Mens Club",
    segmento: "Barbearia",
    regiao: "Ceilândia Norte",
    whatsapp: "(61) 98611-8856",
    instagram: "@menscluboficial",
    status: "lead",
    manutencao: 50,
    contrato: "nenhum",
    infra: {},
    pagamentos: [],
    observacoes: "Mercado super competitivo em Ceilândia → argumento: aparecer primeiro no Google.",
  },
];
